name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    name: 'production'
    runs-on: ubuntu-latest
    steps:
      - name: build
        run: |
          cd ../
          npm i @angular/cli
          npm i
          npm run build-doc
      - name: 'deploy'
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ftp.igordrangel.com.br
          username: koala@igordrangel.com.br
          password: ${{ secrets.FTP_PASSWORD }}
          remoteDir: '/dist'
          local-dir: 'dist/**'
